### PR TITLE
Codius on FeaturePeek

### PR DESCRIPTION
**Pull request by jasonbarry**

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
🎉 Your [FeaturePeek environment](https://dashboard.featurepeek.com/peek/r9zh6o) is ready for your team to preview!

**Review by jasonbarry — COMMENTED** [review]
testing
<details><summary>Browser metadata</summary>

    Page path:     /
    Browser:       Safari 12.1.1 / Mac OS 10.14.5
    Viewport:      1280 x 714 @2x
    Language:      en-US
    Cookies:       Yes

</details>

[View on FeaturePeek](https://dashboard.dev.featurepeek.com/peek/jvghl9#/)

**Review by jasonbarry — COMMENTED** [review]
screenshot of text
<details><summary>Browser metadata</summary>

    Page path:     /docs/using-codius/writing-an-app
    Browser:       Safari 12.1.1 / Mac OS 10.14.5
    Viewport:      1280 x 714 @2x
    Language:      en-US
    Cookies:       Yes

</details>

[View on FeaturePeek](https://dashboard.dev.featurepeek.com/peek/jvghl9#/docs/using-codius/writing-an-app)

**Review by eric-silverman — COMMENTED** [review]
Hey can you change this copy?
<details><summary>Browser metadata</summary>

    Page path:     /
    Browser:       Chrome 74.0.3729.169 / Mac OS 10.14.5
    Viewport:      1400 x 714 @2x
    Language:      en-US
    Cookies:       Yes

</details>

[View on FeaturePeek](https://dashboard.dev.featurepeek.com/peek/jvghl9#/)

**Pull request closed without merging**
